name: routezero
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  # Set for now, as 3.19.0 breaks Stripe integration - the Stripe UI doesn't appear.
  # https://github.com/flutter/flutter/issues/95472
  flutter: 3.19.3

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_riverpod: ^2.1.3
  rxdart: ^0.27.1
  # For displaying maps 
  google_maps_flutter: ^2.3.1
  google_maps_flutter_web: ^0.5.0+1
  # For parsing map related data, e.g. geocoding
  google_maps: ^6.1.0
  pointer_interceptor: ^0.10.1
  provider: ^6.0.3
  equatable: ^2.0.3
  js: ^0.6.3
  uuid: ^4.2.1
  url_launcher: ^6.0.9
  shared_preferences: ^2.0.15
  firebase_analytics: ^10.1.0
  table_calendar: ^3.0.6
  freezed_annotation: ^2.4.1
  retry: ^3.1.1
  fake_async: ^1.3.1
  intl: ^0.19.0
  common_flutter:
    path: ../routezero/common-flutter/package
  routezero_api:
    path: ../routezero/routezero-api-dart/package
  flutter_stripe_web: ^5.1.0
  flutter_stripe: ^10.1.1
  meta: ^1.9.1
  cupertino_icons: ^1.0.5
  font_awesome_flutter: '>=4.7.0'
  string_similarity: ^2.0.0
  timezone: ^0.9.2
  flutter_svg: ^2.0.9
  http: ^1.1.2
  intl_phone_number_input: ^0.7.4
  
dependency_overrides:
  font_awesome_flutter:
    path: ../routezero/font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  freezed: ^2.4.7
  lint: ^2.0.1
  trotter: ^2.0.0-dev.1
  flutter_lints: ^3.0.1
  common_flutter_test: 
    path: ../routezero/common-flutter-test/package
  async: ^2.11.0
  custom_lint: ^0.6.2
  routezero_lints:
    path: ../routezero/routezero-lints

flutter:
  uses-material-design: true