name: test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.19.3

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_stripe_web: ^5.1.0
  flutter_stripe: ^10.1.1
  
dependency_overrides:
  flutter_stripe:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe
      ref: bugfixes-march-2024

  stripe_js:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe_js
      ref: bugfixes-march-2024

  flutter_stripe_web:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe_web
      # Including this ref breaks flutter run
      ref: bugfixes-march-2024

  # Following overrides included just in case needed by above packages, keeping them in sync
  stripe_android:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe_android
      ref: bugfixes-march-2024

  stripe_checkout:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe_checkout
      ref: bugfixes-march-2024

  stripe_ios:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe_ios
      ref: bugfixes-march-2024

  stripe_platform_interface:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: packages/stripe_platform_interface
      ref: bugfixes-march-2024

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true